config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :rentals
  #Landingpage route
  root 'rentals#signin'
  #Rooms route
  get '/rentals/:id', to: 'rentals#show'
  #Search route
  get '/rentals', to: 'rentals#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rental.rb
class Rental < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
	def index
    if (params.has_key?(:destination) && params.has_key?(:rooms))
  		if (params[:destination].length>0 && params[:rooms].length>0)
          @rentals = Rental.where("lower(destination) like ?", "%#{params[:destination].downcase}%").where(rooms: params[:rooms])
      elsif (params[:destination].length>0)
          @rentals = Rental.where("lower(destination) like ?", "%#{params[:destination].downcase}%") 
      elsif (params[:rooms].length>0)  
        @rentals = Rental.where(rooms: params[:rooms])
      else
        @rentals = Rental.all;
  		end
    else
      @rentals = Rental.all;
    end
  end
	def create
  	redirect_to action: :index, destination: params[:destination], rooms: params[:rooms]
  end
	def show
		@rental = Rental.find(params[:id])
 	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YallaSahel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rentals/index.html.erb
 <html lang="en">
    <head>
        <style type="text/css">
            table {
                border-collapse: collapse;
            }

            table, th, td {
                border: 1px solid black;
                text-align: center;
                vertical-align: middle; 
            }
        </style>
    </head>
    <body>

        <!--Search form-->
        <%=form_tag(action: "index") do%>
        Destination: <%= text_field_tag(:destination) %>
        Rooms: <%= number_field_tag("rooms", "", in: 1...21, step: 1) %>
        <%= submit_tag("Search") %>
        <% end %>
        
        <br>

        <!--Rentals table-->
        <table>
            <tr>
                <th>Image</th>
                <th>Url</th>
                <th>Destination</th>
                <th>Owner Name</th>
                <th>Mobile Number</th>
                <th>Rooms</th>
                <th>Bathrooms</th>
                <th>Link</th>
            </tr>
            <% @rentals.each do |rental| %>
            <tr>
                <td><%= image_tag(rental.destination+".jpg", size: "100x100")%></td>
                <td><%= rental.url %></td>
                <td><%= rental.destination %></td>
                <td><%= rental.ownername %></td>
                <td><%= rental.mobilenumber %></td>
                <td><%= rental.rooms %></td>
                <td><%= rental.bathrooms %></td>
                <td><%= link_to 'Show', rental_path(rental) %></td>
            </tr>
            <% end %>
        </table>

        <!--Check logged in-->
        <script type="text/javascript">
        (function() {
            if (typeof(Storage) !== "undefined") {
                if (sessionStorage.name) {
                } else {
                    window.location.href = "https://yallasahel.herokuapp.com";
                } 
            }
        })();
        </script>

    </body>
</html>

app/views/rentals/show.html.erb
 <html lang="en">
    <head></head>
    <body>

    	<!--Rental rooms-->
		<div>Url: <%= @rental.url %></div>
		<div>Destination: <%= @rental.destination %></div>
		<div>Owner Name: <%= @rental.ownername %></div>
		<div>Mobile Number: <%= @rental.mobilenumber %></div>
		<div>Bathrooms: <%= @rental.bathrooms %></div>
		<div>Rooms: <%= @rental.rooms %></div>

        <!--Check logged in-->
        <script type="text/javascript">
        (function() {
            if (typeof(Storage) !== "undefined") {
                if (sessionStorage.name) {
                } else {
                    window.location.href = "https://yallasahel.herokuapp.com";
                } 
            }
		})();
        </script>

    </body>
</html>

app/views/rentals/signin.html.erb
<html lang="en">
  <head>
    <meta name="google-signin-scope" content="profile email">
    <meta name="google-signin-client_id" content="650869901683-b5eobjmol8j16jruue69p9n2jko96jbd.apps.googleusercontent.com">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://apis.google.com/js/platform.js" async defer></script>
    <style type="text/css">
      .welcome{
        display: inline-block;
        text-transform: uppercase;
        color: blue;
        text-decoration: underline;
      }
    </style>
  </head>
  <body>

    <script type="text/javascript">
    //Facebook button code 
      window.fbAsyncInit = function() {
        FB.init({
          appId      : '2011092822272498',
          cookie     : true,
          status     : true,
          xfbml      : true,
          version    : 'v3.2'
        });   
        FB.getLoginStatus(function(response) {
          if (response.status === 'connected') {
            FB.api('/me', function(res) {
              if (typeof(Storage) !== "undefined") {
                sessionStorage.setItem("name", res.name);  
              }
              var text = document.getElementById("welcome").innerHTML;
              text = text.substring(0,31) + res.name;
              document.getElementById("welcome").innerHTML = text;
              document.getElementById("welcome").removeAttribute("style");
            });
          }
        });
      };
      (function(d, s, id){
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) {return;}
        js = d.createElement(s); js.id = id;
        js.src = "https://connect.facebook.net/en_US/sdk.js";
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));

      function afterFbLogin(){
        window.location.reload(true);
      }
    </script>

    <script type="text/javascript">
    //Google button code
      function onSignIn(googleUser) {
        var profile = googleUser.getBasicProfile();
        var id_token = googleUser.getAuthResponse().id_token;
        if (typeof(Storage) !== "undefined") {
          sessionStorage.setItem("name", profile.getName()); 
        }
        var text = document.getElementById("welcome").innerHTML;
        text = text.substring(0,31) + profile.getName();
        document.getElementById("welcome").innerHTML = text;
        document.getElementById("welcome").removeAttribute("style");
      }
    </script>

    <!--FB button-->
    <div id="facebook" class="fb-login-button" data-width="100" data-max-rows="1" data-size="medium" data-button-type="continue_with" data-show-faces="false" data-auto-logout-link="false" data-use-continue-as="false" onlogin="afterFbLogin()"></div>
    
    <br>
    <br>

    <!--Google buton-->
    <div id="google" class="g-signin2" data-onsuccess="onSignIn" data-theme="dark"></div>
  
    <!--Link to search-->
    <div id="welcome" class="welcome" style="display:none"><%= link_to 'WELCOME ', '/rentals'%></div>
      
  </body>
</html>